sudo: required

language: c++

services:
  - docker

before_install:
  - docker build . -t ${TRAVIS_REPO_SLUG}

script:
  - docker run -t -e GITHUB_TOKEN=$GITHUB_TOKEN ${TRAVIS_REPO_SLUG}

branches:
  only:
  - master
