sudo: required

language: c++

services:
  - docker

before_install:
  - docker pull trinhpham/xiaomi-r3g-openwrt-builder

script:
  - chmod +x build_mir3g.sh
  - docker run -t -v $(pwd)/build_mir3g.sh:/src/build_mir3g.sh -e GITHUB_TOKEN=$GITHUB_TOKEN trinhpham/xiaomi-r3g-openwrt-builder

branches:
  only:
  - master
